### ISSUE TITLE
Manual

### ISSUE THREAD

**Issue by nachoan** [hassan-echarif/Airnotifier-Push-Notification-Guide#1]
Hi Echarif,
Could yoy email me the Spanish Documentation please?
My email is nachoan@lasalle.es. Thanks

Saludos,
Podrías mandarnos una copia de la documentación en castellano por favor? Gracias

**Comment by ARATecnica** [comment]
Hi Echarif,

Could you please send me too the document?
My email is: info@aratecnica.it
Thank you so much!
Luigi

**Comment by rec16005** [comment]
Can you mail me the document pls? sebasr9710@gmail.com

**Comment by hassan-echarif** [comment]
@rec16005I sent you the documents but you should know that the instructions are in spanish and also notice that the document is from 4 years ago and maybe some of the technologies used are deprecated now. I hope this helps you.

**Comment by hassan-echarif** [comment]
I will close this issue as I added the documentation to the repository, I will update this documentation to english soon.
